/*
 Quantcast measurement tag
 Copyright (c) 2008-2022, Quantcast Corp.
*/
'use strict';(function(e,t,q){var u=function(b){var c=q.createElement("a");c.href=b;return c},v=[/^http[s]?:\/\/((adservice.google.*)|([^\/]*fls\.doubleclick\.net))\/.*~oref=(?<url>[^;\n]*)/,/^http[s]?:\/\/[^\/]*tealium.*\/.*page_url=(?<url>[^&]*)/],w=function(b){return b.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")},x=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},y=function(b,c,g){return b?"nc"===b?!c||!g||0>c.indexOf(g):"eq"===b?c===g:"sw"===b?0===c.indexOf(g):
"ew"===b?(b=c.length-g.length,c=c.lastIndexOf(g,b),-1!==c&&c===b):"c"===b?0<=c.indexOf(g):!1:!1},a=function(b,c,g){if(t.top!==t.self){try{for(var d=0;d<v.length;d++){var l=q.location.href.match(v[d]);if(l&&l.groups.url){var h=decodeURIComponent(l.groups.url);break}}}catch(r){}h=h?u(h):u(q.referrer)}else h=q.location;h=h.href;y(c,h,g)?b(h):b(!1)},m=function(b,c,g){c=document.getElementsByTagName("meta");for(var d,l,h=[],r=0;r<c.length;r++)if(d=c[r],l=d.getAttribute("name")||d.getAttribute("property"),
l==g){l=h;h=l.concat;var k=g;if(d=d.getAttribute("content")){var p=k;p=-1!==p.toLowerCase().indexOf("tag")||-1!==p.toLowerCase().indexOf("keyword")||0===p.toLowerCase().indexOf("qc:");-1===k.toLowerCase().indexOf("tag")&&-1===k.toLowerCase().indexOf("keyword")&&0===k.toLowerCase().indexOf("qc:")||(d=d.replace(/\.+/g," "));if(p)for(k=d.split(","),d=0;d<k.length;d++)k[d]=w(k[d]);else k=w(d.replace(/,+/g," "))}else k=d;h=h.call(l,k)}0<h.length?b(h):b(!1)},f=function(b){return"array"===x(b)?{labels:b.join(",")}:
{labels:""+b}},n=function(b,c){var g=[],d;if("array"===x(c)){for(d=0;d<c.length;d++)g.push(b+"."+c[d]);return{labels:g.join(",")}}return{labels:b+"."+c}};__qc.apply(null,["rules",[e,null,[[n,"type"]],[[m,"exactmatch","og:type"]]],[e,null,[[n,"author"]],[[m,"exactmatch","article:author"]]],[e,null,[[f,"Salon.Video.videos"]],[[a,"c","salon"],[a,"c","/tv/video"]]],[e,null,[[f,"TV Tropes.Forums"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/topics"]]],[e,null,[[n,"site"]],[[m,"exactmatch","twitter:site"]]],[e,
null,[[n,"section"]],[[m,"exactmatch","article:section"]]],[e,null,[[f,"Salon.News and Politics"]],[[a,"c","salon"],[a,"c","/category/news-and-politics"]]],[e,null,[[f,"Salon.Science and Health"]],[[a,"c","salon"],[a,"c","/category/science-and-health"]]],[e,null,[[f,"Salon.Life Stories"]],[[a,"c","salon"],[a,"c","/category/life-stories"]]],[e,null,[[f,"Salon.Video"]],[[a,"c","salon"],[a,"c","/tv"]]],[e,null,[[f,"TV Tropes.DarthWiki"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/pmwiki.php/DarthWiki/"]]],
[e,null,[[f,"TV Tropes.YMMV"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/pmwiki.php/YMMV/"]]],[e,null,[[f,"TV Tropes.WMG"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/pmwiki.php/WMG"]]],[e,null,[[f,"TV Tropes.Main.Trivia"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/pmwiki.php/Main/Trivia"]]],[e,null,[[f,"TV Tropes.Browse"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/browse"]]],[e,null,[[f,"TV Tropes.Videos"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/recent_videos"]]],[e,null,[[n,"title"]],[[m,"exactmatch","twitter:title"]]],[e,
null,[[n,"tags"]],[[m,"exactmatch","article:tag"]]],[e,null,[[f,"Salon.Culture"]],[[a,"c","salon"],[a,"c","/category/culture"]]],[e,null,[[f,"Salon.Food"]],[[a,"c","salon"],[a,"c","/category/food"]]],[e,null,[[f,"Salon.Video.series"]],[[a,"c","salon"],[a,"c","/tv/series"]]],[e,null,[[f,"TV Tropes.SugarWiki"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/pmwiki.php/SugarWiki/"]]],[e,null,[[f,"TV Tropes.Main"]],[[a,"c","tvtropes"],[a,"c","/pmwiki/pmwiki.php/Main"]]]])})("p-mEzuYq24VEJ-3",window,document);